Hook subscription structure
vagnervst/forum pull request #16
Opened 2018-06-27 22:14 UTC by vagnervst

2018-06-28 14:33 UTC, murilohns requested changes
![image](https://user-images.githubusercontent.com/18074134/42112096-2a0b246a-7bbd-11e8-9f66-b1db6223361c.png)

2018-06-28 14:47 UTC, murilohns commented on helpers/github.js
> +const notifyUserOnIssue = (user, message, { number, repo, owner }) => github.issues.createComment({
Essa assinatura ficou muito estranha o.O

2018-06-28 14:49 UTC, murilohns commented on hooks/githubHook.js
> +  if( repository.full_name !== 'vagnervst/forum-testing' ) {
por que existe esse if aqui?

2018-06-28 15:13 UTC, murilohns commented on subscriptions/issue_comment/verify_content.js
> +issueComment.subscribe(payload => {
nesse caso, é tratado apenas o comentário, não? Por que não usar `comment` como parâmetro, invés de `payload`?

2018-06-28 15:45 UTC, vagnervst commented on helpers/github.js
> +const notifyUserOnIssue = (user, message, { number, repo, owner }) => github.issues.createComment({
Alguma sugestão? Única alternativa que vejo agora é separar em dois objetos, message e issue:

```
notifyUserOnIssue({user, message}, {number, repo, owner})
```

2018-06-28 15:47 UTC, vagnervst commented on hooks/githubHook.js
> +  if( repository.full_name !== 'vagnervst/forum-testing' ) {
A ideia é limitar o script para funcionar só pra um repositório, pois caso alguém descubra a URL do hook, a aplicação ignore pelo nome do repositório.

Seria melhor passar esse nome pra uma environment variable.

2018-06-28 15:47 UTC, murilohns commented on helpers/github.js
> +const notifyUserOnIssue = (user, message, { number, repo, owner }) => github.issues.createComment({
`notifyUserOnIssue(user, message, issue)`

e no corpo da função:

`issue.user`, `issue.repo`, `issue.owner`

2018-06-28 16:26 UTC, vagrantsn commented on helpers/github.js
> +const notifyUserOnIssue = (user, message, { number, repo, owner }) => github.issues.createComment({
Ela já é assim hoje, é que usei destructuring na assinatura:

```javascript
const notifyUserOnIssue = (user, message, { number, repo, owner })
```
É o mesmo que:
```javascript
const notifyUserOnIssue = (user, message, issue) => {
  const { number, repo, owner } = issue
}
```
Ou
```javascript
const notifyUserOnIssue = (user, message, issue) => {
  const number = issue.number
  const repo = issue.repo
  const owner = issue.owner
}
```

2018-06-29 11:13 UTC, murilohns commented on .env.sample
> +MONGO_HOST=
Por que não usar só uma variável? Nela colocamos a porta

2018-06-29 17:21 UTC, vagnervst commented on .env.sample
> +MONGO_HOST=
Quando utilizávamos uma única variável era sempre muito confuso o que deveria ou não ser informado, dessa forma fica mais claro o escopo de cada uma delas, ao mesmo tempo que mantém o valor default de cada uma utilizando as configs do convict:

https://github.com/vagnervst/forum/blob/feature/add-hook-subscription-structure/config.js#L14

2018-06-29 19:54 UTC, murilohns commented on .env.sample
> +MONGO_HOST=
show!

2018-06-29 19:55 UTC, murilohns commented on .env.sample
> +MONGO_HOST=
show!

2018-06-29 19:56 UTC, murilohns commented on docker-compose.yml
>      ports:
esse docker-compose ainda funciona?

2018-06-29 19:56 UTC, murilohns commented on hooks/hook.js
> +    fn,
o que significa fn?

2018-06-29 20:02 UTC, vagnervst commented on docker-compose.yml
>      ports:
Fununcia

2018-06-29 20:04 UTC, vagnervst commented on hooks/hook.js
> +    fn,
Abreviei `function` em `fn`. Nesse caso é o callback que será executado quando o evento do hook disparar

2018-07-03 12:47 UTC, murilohns approved these changes

2018-07-05 02:35 UTC, merged